name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dedde8ae2e61413facf818ca6aefa74a37d443edbe6800bf463908ce160b4ff8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
