name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "887194176c37a4804fcc2b578af012a688b212e3540f486765126aca3f23be85"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
