name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82b3622bf969b562e65f4ba3eb8225b9edc31308a4bf6e4245a9acb46c21d0d5"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
