name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0f83ba9b60d999daa7ace90f4cac4be81b035bf3aabd6e780634e5a3c5bfbef"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
