name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b763abbdc7ff1f4fb00befec82a09e9e66b50ef646ee10467936c92fcd4f0b8"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
