name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa1ed0e80e70292fd1050127e68f1f8b455188f342d9f4296d291ca52f0e09e4"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
