name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f758fc4caa3fbf90b149596b4ea3830e5eca9d9cc551ef2b106e02556769fba"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
