name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5eff74f90dd09bb81c39510c182cdb402d7162cb5121557d8c130037efa3f6a6"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
