name = "vpserverfiles"
author = "dog"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7e03e26c37c56b661d4bbc3f1b2411ca18237f25dc1cb3e9f824a2f74f85f8e"

[versions]
forge = "40.2.21"
minecraft = "1.18.2"
