
#ServerConfigs for VaultAdditions
["General Settings"]
	#Modify the amount of blocks a Power Crystal increases with its usage
	POWER_CRYSTAL_INCREASE = 1
	#The multiplier when increasing the border inside the Nether
	NETHER_BORDER_INCREASE = 0
	#The multiplier when increasing the border inside the Nether
	END_BORDER_INCREASE = 0
	#Whether there should be a time limit on when to prevent Border Expansion
	LIMIT_TIME_FOR_EXPANSION = false
	#The date when Gemstones will no longer be accepted by the Globe Expander, based off of Local server time. (TT/MM/YYYY, HH:MM:SS)
	STOP_ACCEPTING_GEMSTONES_DATE = "25/02/2025 20:00:00"
	#Whether players should grow in size whenever Gemstones are submit (Does not grow player hitbox)
	GROW_PLAYER_ON_GEMSTONE_SUBMIT = false
	#The amount to grow the player by whenever they submit a gemstone, per gemstone
	GROW_PLAYER_AMOUNT = 0.001
	#The max amount a player can grow in total
	GROW_PLAYER_CAP = 0.5
	#Whether the Power menu should be shown to the player
	SHOW_POWER_MENU = false

